### ISSUE TITLE
Unable to locate package google-chrome-stable. Exit code 100

### ISSUE THREAD

**Issue by Sakarii** [JBetula/flyboylog#1]
6.476 Reading package lists...
7.102 Reading package lists...
7.726 Building dependency tree...
7.913 Reading state information...
7.922 E: Unable to locate package google-chrome-stable
------
failed to solve: process "/bin/sh -c apt-get update && apt-get install gnupg wget -y &&   wget --quiet --output-document=- https://dl-ssl.google.com/linux/linux_signing_key.pub | gpg --dearmor > /etc/apt/trusted.gpg.d/google-archive.gpg &&   sh -c 'echo \"deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main\" >> /etc/apt/sources.list.d/google.list' &&   apt-get update &&   apt-get install google-chrome-stable -y --no-install-recommends &&   rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 100

**Comment by JBetula** [comment]
unable to replicate error
